### ISSUE TITLE
Meteo France now ignores the lang setting and shows labels in French

### ISSUE THREAD

**Issue by Mrnofish** [Akylas/oss-weather#137]
After the last update (1.12.4 b 106) it seems using Meteo France results in the language setting being ignored, all weather statuses are shown in French.

Setting the app to auto or explicitly to English has no effect.

Switching to OM, the labels revert to English.

**Comment by ChrisRenfrow** [comment]
I came here to report this behavior as well.

**Comment by farfromrefug** [comment]
@ChrisRenfrow @Mrnofish it will be fixed in next version. Keep in mind that there is an issue with MF api though. Even in english, first days of daily forecast description is returned in french

**Comment by ChrisRenfrow** [comment]
Would it be appropriate to open an issue in the Meteo France repository (https://github.com/hacf-fr/meteofrance-api)?

**Comment by Mrnofish** [comment]
Haha, how very French!

That's technically not an issue for me, since mf's model doesn't seem accurate enough for my country.

The swift response is however very appreciated, keep up the good work!

**Comment by farfromrefug** [comment]
it is fixed in latest

**Comment by Mrnofish** [comment]
It does seem that the issue is back in 2.4.4 Build 123 (but I only noticed because of #189)

As mentioned previously I don't need a fix, this is just a FYI.

**Comment by farfromrefug** [comment]
@Mrnofish I think the issue is on MeteoFrance. It has always been like that. Usually the first 2 days of the forecast are in English then others are in French. 
Sadly we can't really do anything about that. We can't event really report it to the risk that météo france blocks that API(api not documented) that everyone is using with the same api key...
