### ISSUE TITLE
Export/Import Settings toggle

### ISSUE THREAD

**Issue by ghost** [Akylas/oss-weather#182]
Export and import settings when clicked, do nothing on iOS.

**Comment by jacobgonzales20** [comment]
> And indeed, a window appears on the screen indicating that the storage reading permission is missing. ![Screenshot_20240527-182352_OSS Погода](https://private-user-images.githubusercontent.com/140940260/334152385-cb6d354e-96db-4085-9529-1fd72a81d91f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjQxOTQsIm5iZiI6MTcxNjgyMzg5NCwicGF0aCI6Ii8xNDA5NDAyNjAvMzM0MTUyMzg1LWNiNmQzNTRlLTk2ZGItNDA4NS05NTI5LTFmZDcyYTgxZDkxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxNTMxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGQ0Nzk2ZmQ2ZGY1Y2UzYTZmYmIzZjg2NDI3YjY4Y2QxMzQwM2QwZjA0ZTkxMzk4OGE1NjhiOTY3NWY2NjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VmUppFdNM5YUmLxczHd0yRWoYJvekv5MLZNUK8nXmhg)
> 
> Forgot to mention, version 2.4.2.121

Getting no response on iOS, OSS Weather v. 2.3.1

https://github.com/Akylas/oss-weather/assets/122128828/cb577aac-38c0-4892-b6e4-01b6ef8c4940

**Comment by farfromrefug** [comment]
> And indeed, a window appears on the screen indicating that the storage reading permission is missing.
> ![Screenshot_20240527-182352_OSS Погода](https://github.com/Akylas/oss-weather/assets/140940260/cb6d354e-96db-4085-9529-1fd72a81d91f)
> 
> Forgot to mention, Android version 2.4.2.121

What's your android version ?

**Comment by farfromrefug** [comment]
@TenchMaviatorius2759 should be fixed in latest release

**Comment by jacobgonzales20** [comment]
> @TenchMaviatorius2759 should be fixed in latest release

I'm not sure if 2.3.2 Build 104 is the latest for iOS but export settings is still broken

**Comment by farfromrefug** [comment]
> > @TenchMaviatorius2759 should be fixed in latest release
> 
> I'm not sure if 2.3.2 Build 104 is the latest for iOS but export settings is still broken

Always look at the changelog when i say a bug is fixed. iOS latest is waiting for review right now. I just tested again with the published version and export settings is working there
