### ISSUE TITLE
Skipped Day in Week View

### ISSUE THREAD

**Issue by LinuxinaBit** [Akylas/oss-weather#264]
A day (Wednesday) is completely skipped in the week view with the "Show current day in daily list" option disabled:

![Screenshot_20241210-180532-796](https://github.com/user-attachments/assets/a68d1517-c7b7-4a0d-b07b-1ee4b8e64d72)

It goes from Tuesday (the current day) straight to Thursday.

Version 2.9.2 build 145

**Comment by farfromrefug** [comment]
@LinuxinaBit is it still the same after a full app restart?
which provider? can you export settings and share with me? You can share by email (cause it will have your location)

**Comment by LinuxinaBit** [comment]
Unfortunately I did a reinstall and it’s fixed now (of course) and I can’t reproduce it.
Maybe it’s a weird timezone thing, I’ll check later tonight.
Otherwise I’ll just close this, sorry about that 😅

**Comment by farfromrefug** [comment]
@LinuxinaBit think the issue is still there. if you see it again let me know and share your settings

**Comment by LinuxinaBit** [comment]
Ah, ok. I’ll let you know 👍

**Comment by farfromrefug** [comment]
@LinuxinaBit i rewrote the timezone handling. Might fix that too

**Comment by 0-5-0** [comment]
Seems to be fixed with the latest release (154)
