### ISSUE TITLE
[English] Label improvement suggestions

### ISSUE THREAD

**Issue by Mrnofish** [Akylas/oss-weather#300]
Under Preferences > Weather Data:

- Some metrics use Proper Case (e.g. "Air Quality Index", "Sealevel Pressure"), while for most only the first letter is capitalized (e.g. "Beaufort wind scale").
- "Uv Index" > "UV Index/index"
- "snowDepth" > "Snow Depth/depth"
- "Dewpoint" > "Dew Point/point"
- "Sealevel pressure" >"Sea-level Pressure/pressure" 

- "UV index below won't be shown" > "UV Index won't be shown [if] below"

Under Preferences > Charts

- There's a typo in "Show wind speed in main view hou*lr*y chart"

For improved clarity, "Show hourly chart in [main|daily] view" could be changed to something like "Fit entire hourly chart in [main|daily] view" since the hourly chart is always displayed nevertheless.

Under Preferences > Units:

The "Unit" word is present is 4 out of 5 labels. Since the heading reads Custom Units and the menu is called Units, this seems superfluous.

Under Geolocation:

- "Find location and weather on every pull-to-refresh" could be changed to "on every manual refresh". While it sounds better in English (I think), it does not make explicit how to trigger a manual refresh. That gesture is part of the standard interaction language, so it's probably OK.

**Comment by farfromrefug** [comment]
@Mrnofish thanks for all of that! I will fix all.
About the "improved clarity".the thing is the default view is actually not a chart, but i get your point. Maybe something like "alternate hourly layout with full data fit" or something like this?

For geolocation, i agree, not sure what would be best

**Comment by farfromrefug** [comment]
@Mrnofish i think i looked at almost all of them except maybe the "improved clarity". Can you confirm?

**Comment by Mrnofish** [comment]
It's more consistent now. 

Uv, snowDepth, Dewpoint and Sealevel still enoloy non-standard forms.

On pull-to-refresh I stand by my previous suggestion. For "show hourly chart.." the app is already using the word chart for that se two options, so I'm not sure I appreciate the meaning of your remark?

The altenative you proposed doesn't sound very good to my ear either. Since I'm EASL too, maybe a native speaker such as @0-5-0 could chime in.

For the new option "use odd background colors in hourly section" my suggestion would be more along the lines of "Alternate background colors in Hourly charts."

**Comment by farfromrefug** [comment]
@Mrnofish @0-5-0 thanks a lot for both of you for your input. Your contribution to that app is quite amazing!
for "refresh" i went for `Fetch current location when swipping down on main view`

I also went for `Show alternate hourly layout on (main/daily) view` which i like a lot.

I also indeed move most "charts" settings to hourly as they only apply to hourly charts.

Awesome!

**Comment by 0-5-0** [comment]
I mistyped swipping, apparently it's "swiping" (one p), for the Geolocation option.

Just looking at the Weather data settings "Uv Index" should be "UV Index" (with a capital V as well).

The rest looks good :), thanks again!

**Comment by farfromrefug** [comment]
@Mrnofish ahah did not even check and simply copied ;)

**Comment by Mrnofish** [comment]
Just occurred to me there's a bunch more inside Compare Models:

| Currently | Proposed Change |
|---|---|
| precipProbability | Precipitation [ Probability | Chance | % ] |
| windBearing | Wind Bearing |
| Rain_Precipitation | Rain Precipitation |
| Uv index | UV Index |
| temperature | Temperature |
| temperatureMin | [Minimum Temperature | Min Temperature | Min Temp | Temperature Low | Temp Low] |
| temperatureMax | [Maximum Temperature | Max Temperature | Max Temp | Temperature High | Temp High] |

I've used Title Case since the other items are spelled in the same way, however there are large parts of the app which use Sentence Case. Since I needed to look up the letter case variations, [here's a Wikipedia explainer](https://en.wikipedia.org/wiki/Letter_case).

**Comment by 0-5-0** [comment]
The release from yesterday has fixed most of the Compare Model labels but at the top there's still:

precipProbability, Wind_bearing and there seems to be 2 "Precipitation" entries. The rest look good.

**Comment by farfromrefug** [comment]
@0-5-0 thanks! last points fixed and will be in next release

**Comment by Mrnofish** [comment]
BTW the labels used by the legend are completely differenti by those in the selection pane, so there are mamy more adjustments to be done there, too.

**Comment by farfromrefug** [comment]
@Mrnofish Should be fixed in latest version

**Comment by 0-5-0** [comment]
I guess the wording in yellow/orange would need the same modifications for the compare models page. If I select Wind Speed as an example using the check box then on the actual page it's still showing **windSpeed** km/h (Hourly) so would probably need to match.

There's also no indicator where you have the checkboxes that the first column is hourly and second column is daily.

<img src="https://github.com/user-attachments/assets/cb9ff98f-95ad-478e-ad91-1e996020178d" width=45% height=45%>
<img src="https://github.com/user-attachments/assets/a776f1fc-72e3-426f-aad1-4dc90bcdf5b5" width=45% height=45%>

**Comment by farfromrefug** [comment]
@0-5-0 thanks will fix yellow label. About hourly/daily checkbox,i could not find how to "show it" as there was not enough space for those labels :P Might fix that in september

**Comment by 0-5-0** [comment]
Created https://github.com/Akylas/oss-weather/issues/349 for the hourly/daily checkbox labels just to not keep this issue open if/when it's ready to be closed.
