### ISSUE TITLE
Daily and hourly forecast details inconsistent

### ISSUE THREAD

**Issue by s38b35M5** [Akylas/oss-weather#84]
When looking at Monday's forecast high temp (today being Saturday) for a given location, I see a high/low temp of 68F/82F. 

If I scroll along the hourly forecast to Monday, the temp gets as low as 71F up to 88F.

![Screenshot_20240203-140121_OSS Weather_1](https://github.com/Akylas/oss-weather/assets/138058715/35a28928-8f64-43d7-9129-68919e0047eb)

Here is another example, with Portland Maine USA
![Screenshot_20240203-140330_OSS Weather_1](https://github.com/Akylas/oss-weather/assets/138058715/60e3df34-5ade-4245-8173-76293506bce4)

Are these forecasts coming from different sources? Why don't they match? Which is to be trusted?

**Comment by farfromrefug** [comment]
@s38b35M5 Thanks for the detailed report. Seems to be an issue with Open-Meteo as i get those values directly from there. I will report it there

**Comment by s38b35M5** [comment]
Great app. It's so nice to have a weather app that doesn't sit for 10 seconds before loading while it scrapes my device and loads trackers.

**Comment by farfromrefug** [comment]
@s38b35M5 thanks a lot we share the same feeling ;)

**Comment by farfromrefug** [comment]
@0-5-0 @s38b35M5 i think this issue is related to Open Meteo https://github.com/open-meteo/open-meteo/issues/642. It would be worth checking if this is still an issue today as Open Meteo is constantly improving

**Comment by 0-5-0** [comment]
The timezone bug aside (which should be fixed by now), there was also some changes to feels like temperature stuff in the latest release. If you're using "Show Feels like" in the settings you could see if it makes a difference with it on/off.

**Comment by s38b35M5** [comment]
Still isn't matching, though I see "today" is no longer present in the long range forecast. Going only by the high/low for today in the top right and the hourly temp estimates, there's still a noticeable difference.

![Screenshot_20241206-113925_OSS Weather_1](https://github.com/user-attachments/assets/8f7ae649-c176-4ba6-b15b-0f9837804324)

**Comment by s38b35M5** [comment]
I meant to add that I don't use the feels like setting.

**Comment by farfromrefug** [comment]
@s38b35M5 Yes your error seems unrelated to feels like. Could you try something for me? in preferences/weatherdata. Could you enable "show current day in daily list"?
Then share a screenshot like you did with current top min max does not correspond. I want to see if it also not correspond on the daily list for the current day

**Comment by 0-5-0** [comment]
I can reproduce the same issue on my device. I tried a few locations, Grenoble France, Toronto Ontario, Portland Maine.

Note that I have the "Use feels like" turned on and I'm using celcius instead of fahrenheit but the issue occurs with it on/off or with/without celcius/fahrenheit as well.

In the 2-3 days that I could see under hourly for Grenoble it hit the forecasted min/max temperature at some point throughout those days on each of the days, so no issues when testing with Grenoble.

In the 2-3 days for Toronto under hourly it hit the daily forecasted min/max temperature on 1 of 3 then 2 of 3 it doesn't quite reach it or goes above it when scrolling through the hourly section.

Monday shows it's forecasting a high of 0 but it hits a high of 2 when scrolling through the hourly view, Tuesday is fine, then Wednesday it forecasts a high of 1 but only hits 0, it does hit the low:

<img src="https://github.com/user-attachments/assets/316efe40-b834-4998-a8c9-76c999bcd91e" width=45% height=45%>
<img src="https://github.com/user-attachments/assets/54be6cf2-a4d2-4f96-a55c-eb14e5f0f1b6" width=45% height=45%>

In the 2-3 days for Portland under hourly it doesn't quite reach the high or low on all 3 days or goes above it when scrolling through the hourly section.

Monday it forecasts a daily high of -1 but shows -3 under hourly, Tuesday it forecasts a high of -3 but hits -2, and Wednesday it forecasts a low of -3 but only hits -2:

<img src="https://github.com/user-attachments/assets/76c2f1b4-1a93-4fed-8dc0-676f438cae4d" width=45% height=45%>
<img src="https://github.com/user-attachments/assets/c7a2de14-217e-48b6-88e4-d698b1503ac5" width=45% height=45%>
<img src="https://github.com/user-attachments/assets/e5bd88f2-953a-4868-a7ed-db502b33da48" width=45% height=45%>

Not sure if there's rounding somewhere affecting this, Portland and Toronto are in the same timezone/have the same time.

**Comment by farfromrefug** [comment]
@0-5-0 thanks a lot for the testing! it confirms what i think which is that the issue comes from Open-Meteo. he knows about it. Not sure if he has plan to fix it

**Comment by 0-5-0** [comment]
I'm wondering if this might be fixed in yesterday's release (build 161), issue #331 was for a similar problem between the current forecast and the daily forecast where this issue was between daily and hourly however I've just gone through the next 4 days forecasts for 4 wildly different locations that I use for testing and all the min/max numbers match now between hourly and daily.

Is it fixed for you with the release from yesterday?

**Comment by farfromrefug** [comment]
@0-5-0 could fix the top weather forecast(current) being not "sync" with hourly chart. However for the daily view i still think it is an Open Meteo issue. Sadly no change there

**Comment by s38b35M5** [comment]
> I'm wondering if this might be fixed in yesterday's release (build 161), issue [#331](https://github.com/Akylas/oss-weather/issues/331) was for a similar problem between the current forecast and the daily forecast where this issue was between daily and hourly however I've just gone through the next 4 days forecasts for 4 wildly different locations that I use for testing and all the min/max numbers match now between hourly and daily.
> 
> Is it fixed for you with the release from yesterday?

It is fixed for me at the three locations I follow. The today min/max matches below, and the hourly scroll through days matches as well. I use Open-Meteo as provider and all seems correct and matching.

As far as my original issue is concerned, I see it as resolved on v.2.10.11_161.

Thank you for your work!
